services:
  - type: web
    name: playtimeusa-backend
    env: node
    plan: starter          # or free, standard, etc.
    region: oregon         # pick your region
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    healthCheckPath: /health

    # Node version is pinned in package.json "engines": { "node": "20.x" }

    envVars:
      # Secrets: set values in the Render dashboard after first deploy.
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_KEY
        sync: false
      # Non-secrets you want tracked in git:
      - key: FRONTEND_ORIGIN
        value: "https://playtimeusa.net,https://games.playtimeusa.net"
